//
//  painting.swift
//  Artector
//
//  Created by Lujain Yhia on 11/06/1445 AH.
//


import Foundation
struct Painting: Identifiable {
    var id = UUID()
    var name: String
    var artist: String
    var artistStory: String
    var paintingStory: String
    var paintingDescription: String
    let test = NSLocalizedString("findBug" , comment : "")
    
//    var artistStoryAr : String
    
}







let paintings = [
    "Fosa": Painting(name: NSLocalizedString("Fosa (The Pit), 2022", comment: "") , artist: NSLocalizedString("Iosu Aramburu", comment: "") , artistStory: NSLocalizedString("The work of Iosu Aramburu (born in Lima in 1986) revolves around modernity as an aesthetic, architectural and philosophical paradigm. From the reinterpretations of modern languages, Aramburu seeks to question the failures of the modern project" , comment:  ""), paintingStory :  NSLocalizedString("Fosa is part of series in which Iosu Aramburu revists photographs and engravings of 19th and 20th century archaeological explorations in Peru, where ambitous state-funded excavations were pivotal in crafting and shaping the recently independent country's national identity. Aramburu's paintings focus on images of conflict and confrontation between different times, where scientists, politicians, collectors and museum workers pose against artifacts and landscapes that represent the distant past. From the perspective of the landscape, archeaology shares many similarities with mining. The paintings highlight how the pursuit of archeaological knowledge can result in dispossession, appropriation and displacement." , comment: "")  , paintingDescription: NSLocalizedString("Oil on canvas. In Fosa, a party of archaeologists stand above the ground that holds the history they aim to unearth. This painting depicts a group of abstract, geometrically-styled figures in formal attire, standing in a cool-hued, mountainous terrain. The contrast of warm sunlight against the blues and greys of the landscape adds depth. Faces are indistinct, emphasizing the figures' contemplative stance within the expressive brushwork of the surroundings. The overall mood is introspective and solemn." , comment: "")),
    
    
    "Dark sea": Painting(name: NSLocalizedString( "Dark Sea, 2016", comment:  ""), artist: NSLocalizedString( "Zarina", comment:  "") , artistStory: NSLocalizedString( "Zarina Hashmi, who prefers to be called by just her first name, has a love for paper: “Paper is an organic material, almost like human skin,” she says. She uses the material to create prints, drawings, and even sculptures cast in paper pulps. Zarina received her degree in mathematics before continuing her studies as a printmaker in Bangkok, Tokyo, and Paris. To date, her various methods of printmaking have included intaglio, woodblock, lithography, and silkscreen. She works in series, creating several prints in order to articulate and explore the multiplicity of a concept. Her recurring themes include diaspora, nostalgia, memory, borders, and home; her subjects are those inspired by her own understanding of her surroundings and history. She also uses a combination of punctures, folds, cuts, and scratches to create textured surfaces.", comment:  "") , paintingStory: NSLocalizedString("As a child, Zarina experienced the 1947 partition of the indian Subcontinent firsthand. like thousands of others, her family was displaced to a refugee camp to escape widespread violance. She felt a lifelong affinity with displaced peoples, often expressing solidarity through her printed work. In 2015, she was moved by the persecution of Rohingya Muslims in Myanmar and the hardships of their difficult passage into neighboring Bangladesh. She linked these with perilous journeys by boat to reach the borders of Europe, drowning thousands in the Mediterranean every year. This led to her body of work, Dark Sea, in reference to the darkness experienced by refugees crossing the sees at night on small boats to avoid being caught by border patrols.", comment:  "") , paintingDescription: NSLocalizedString( "Indian handmade paper stained with Sumi ink mounted on Arches Cover buff paper. In the prints displayed here, Zarina superimposed strips of paper to recreate what can be interpreted as a passenger's perspective at sea at night. The curved shape repeated at the bottom of both images, evokes the stern of a boat. It is surrounded by darkness except for what appears to be lights on the horizon, a very distant glimmer of hope.", comment:  "")),

    
    "Blind Light": Painting(name: NSLocalizedString( "Blind Light, 2017", comment:  "") , artist: NSLocalizedString( "Daniele Genadry" , comment:  "") , artistStory: NSLocalizedString( "********", comment:  "") , paintingStory: NSLocalizedString( "Drawing inspiration from photographs, Daniele Genadry blends the photographic record, memory and histories of landscape painting into her work. Her paintings illustrate a highly individual and personal approach to painterly depictions of landscapes.", comment:  "") , paintingDescription: NSLocalizedString( "Acrylic and oil on canvas. In Blind Light, Genadry transformed the flowing water of a waterfall, which reflects light much more than the surrounding mountains, into a radient beam of light that seams to slice through the rocks." , comment:  "")),


"Untitled (Desert series)": Painting(name: NSLocalizedString(  "Untitled (Desert Series), 1981-1982" , comment:  "") , artist: NSLocalizedString(  "Arif El Rayess ", comment:  "") , artistStory: NSLocalizedString(  "Lebanese artist Arif El Rayess lived in Saudi Arabia from 1981 to 1989, during which he spent time in Jeddah, Riyadh, Tabuk and Al-Madinah Al-Munawwarah. An itinerant and prolific artist, he engaged with sculpture and architecture in a post-oil boom Saudi Arabia, where the kingdom's main cities were undergoing major beautification projects. ", comment:  "") , paintingStory: NSLocalizedString(  "El Rayess participated in the Jeddah embellishment intiated by then-mayor Mohammed Sayed Farsi, in collaboration with architect Julio Lafuente. The result of this years-long initiative is often referred to as an (open-air museum) and includes sculptures by invited Arab and international artists. El Rayess' 28-meter-high aluminuim sculpture Column of Light (1981), representing the word (Allah) (SWT), is still visible on a square on Palestine street in Jeddah. The artist's engagement with sculpture and architecture was influenced by his close relationship with architects Hassan Fathy and Fredrich Kiesler, and he produced numerous drawings, models and utopian architectural sketches. Captivated by the light of the Arabian desert, El Rayess a significant series of over 300 hundred landscapes, including paintings and drawings. In Tabuk, he photographed the rock formation of its mountains, villages and ancient ruins. All these elemnts feature in his landscapes as he seeks to capture the desert's changing light, vastness and spiritual dimensiom. El Rayess refers to these formal expiremnts as (Marhalat Al-Noor) or the (Period of Light), during which he undertook numerous studies and trials in capturing the light of the desert." , comment:  ""), paintingDescription: NSLocalizedString(  "Oil on canvas. his artwork presents a stylized desert landscape with a mixture of architecture and nature. In the foreground, there's a vibrant green strip of vegetation, possibly farmland. The middle ground features an assortment of buildings with simple, modernist shapes. Some resemble traditional dwellings, while others are more abstract, geometric forms. In the background, muted brown mountains rise under a pale sky, giving a sense of vast, open space. The color palette is subdued, with the exception of the greenery, which stands out against the earthy tones. The painting is set against a warm, orange backdrop that frames and accentuates the desert hues.", comment:  "")),


"Untitled 1987": Painting(name: NSLocalizedString( "Untitled, 1987", comment:  "") , artist: NSLocalizedString( "Abduljabbar Alyahya", comment:  "") , artistStory: NSLocalizedString( "********" , comment:  ""), paintingStory: NSLocalizedString( "In Untitled, the relationship between the Arab man and his heritage and his surroundings is depicted through his signature style of calculated portions of color. Th transperant figure, gazes over the Najd village, symbolizing his relationship with his legacy. Beneath him, there is a grounded curled-up female figure.", comment:  "") , paintingDescription: NSLocalizedString( "Oil on canvas. The painting portrays an abstracted landscape with a dichotomy of nature and architecture. In the foreground, lush greenery suggests fertile land, while the background consists of soft brown mountains under a light sky. Between these two, various geometric and modernist structures in muted colors are scattered across a desert-like expanse, suggesting human habitation or industry amidst the vastness. The overall palette is dominated by earth tones with a splash of green, conveying a serene yet perhaps surreal scene.", comment:  "")),
    
    
    "The land of solidities": Painting(name: NSLocalizedString( "The Land of Solidities, 1970", comment:  "") , artist: NSLocalizedString( "Mounirah Mosley", comment:  "") , artistStory: NSLocalizedString( "Mounirah Mosley explores unconventional mediums in her practice. She expiremnts with various materials such as handmade paper, natural dyes, copper, palm trees, wood and papyrus to create vibrant works that reflect Saudi traditions. Mosley connects her personal experiences and observations to broader social and political contexts." , comment:  ""), paintingStory: NSLocalizedString( "The Land of Solidities (1970) may suggest a commentary on gender roles, or identity. It pays homage to the art historical tradition of including women in the landscape. Th e expressive color palette of the painting evokes the rich visual and cultural landscape of Saudi Arabia. This use of color creates a sense of tranquility of the natural surroundings. In the foreground, there is a figure resembling a woman fully covered with a black abaya, exuding mystery and anonymity. The presence of the necklace indicates personal expression despite the covered appearance.", comment:  "") , paintingDescription: NSLocalizedString( "Oil on wood ###", comment:  "")),
    
    "Thursday Market": Painting(name: NSLocalizedString( "Thursday Market, 1980", comment:  "") , artist: NSLocalizedString( "Taha Alsabban", comment:  "") , artistStory: NSLocalizedString( "#" , comment:  ""), paintingStory: NSLocalizedString( "In Thursday Market (1980), Alsabban offers insight into the bustling Thursday markets in Abha, where women engage in selling activities. Employing abstract geometric shapes, Alsabban interconnects architectural motifs, encapsulating the memory of the place. The human figures, positioned along the street, intertwine with the buildings, forming a harmonious visual narrative.", comment:  "") , paintingDescription: NSLocalizedString( " Oil on canvas #", comment:  "")),
    
    
    "Still life with fish ": Painting(name: NSLocalizedString( "Still Life with Fish, 1975", comment:  "") , artist: NSLocalizedString( "Abdulhalim Radwi", comment:  "") , artistStory: NSLocalizedString( "He was born in Mecca in 1939, and lived as an orphan of his father since the age of five, growing up in a poor family. He completed his general education in Mecca and assumed responsibility as the eldest sibling in his family since the age of nine, where he worked in selling balila (a Hejazi dish), guiding pilgrims, and meeting the needs of Hajj pilgrims. He graduated from Al-Aziziya School in 1960. His talent began to emerge early on and he expressed it at the Saudi Scientific Institute in 1958. Driven by the ambition to travel abroad and pursue higher studies, he went to Italy, specifically to the Academy of Fine Arts in Rome." , comment:  ""), paintingStory: NSLocalizedString( " In Still Life with Fish (1975), Radwi employs a combination of paint and sand. resulting in a flattened portrayal of two fish within a loosely arranged geometric framework. Still Life with Fish pays homage to the origins of the still life genre, as fish were frequently depicted in early still life compositions.", comment:  "") , paintingDescription: NSLocalizedString( "This painting showcases an abstract composition using a limited color palette, primarily in shades of blue, black, white, and beige. It features geometric shapes and forms that vaguely suggest elements of a still life, possibly including a fish and a bottle. The outlines are soft and blend into the background, while the juxtaposition of forms creates a sense of depth. The signature 'Radwi '75' indicates the artist's name and the year of creation. The artwork employs a cubist influence in its fragmentation and reassembly of objects within the space, giving it a modern and timeless quality.", comment:  "")),
    
    
    "Untitled 1988": Painting(name: NSLocalizedString( "Untitled, 1988", comment:  "") , artist: NSLocalizedString( "Taha Alsabban", comment:  "") , artistStory: NSLocalizedString( "#" , comment:  ""), paintingStory: NSLocalizedString( "#", comment:  "") , paintingDescription: NSLocalizedString( "Oil on canvas. Untitled (1988) presents a night of jubilation, as men stand holding the (teeran), a traditional Arabic percussion instrument. The men, dressed in local attire, become part of a vibrant tableau. The focal point lies at the center of the composition, with men and their drums arranged in a flowing formation, while the background fades Into a washed-out orange hue.", comment:  "")),
    
    
    "Our generous land": Painting(name: NSLocalizedString( "Our Generous Land (The Spring of Generousity), 1980", comment:  "") , artist: NSLocalizedString( "Saad Almasari", comment:  "") , artistStory: NSLocalizedString( "Saad Almasari's works span various mediums and styles, including ceramics, bronze sculptures, oil paintings, watercolors and acrylics. He draws inspiration from memories, local heritage, architecture, socitey and the Saudi environment. The artist integerates the flatness of traditional islamic arts and infuses modernity by incorporating optical illusions.  " , comment:  ""), paintingStory: NSLocalizedString( "#", comment:  "") , paintingDescription: NSLocalizedString( "Oil on canvas. In 'Our Generous Land' (1980), Almasari depicts the land, desert dunes, and mountains in an abstract way. Employing a color palette of reds and blues with geomatric shapes and sharp lines, he harmonises the convergence of spaces. The geomatric shapes also contribute to the optical illusion that he seeks to achieve. ", comment:  "")),
    
    
    "Builders": Painting(name: NSLocalizedString( "Bullders, 1977", comment:  "") , artist: NSLocalizedString( "Abdulrahman Alsoliman", comment:  "") , artistStory: NSLocalizedString( "Abdulrahman Alsoliman draws inspiration from the various urban and industrial landscapes of the Al-Ahsa region. His work navigates between different styles Including cubism, realism, abstraction, and surrealism. In the 1980s, Alsoliman explored historical, traditional, and societal shifts in Saudi Arabia." , comment:  ""), paintingStory: NSLocalizedString( "#", comment:  "") , paintingDescription: NSLocalizedString( "Oil on canvas. In Bullders (1977), two men are depicted wearing traditional attire as they carry construction materials. Alsoliman employs a Cubist style to transform the two builders into angular forms that intersect and overlap.", comment:  "")),
    
    
    "Composition": Painting(name: NSLocalizedString( "Composition 1 and Composition 2, 1988", comment:  "") , artist: NSLocalizedString( "Abdullah Hammas ", comment:  "") , artistStory: NSLocalizedString( "Abdullah Hammas is a prominent Saudi artist who is recognized as a pioneer of the fine art movement in Saudi Arabia. His works are celebrated for their symbolic abstraction, where he seeks to depict the real world in abstract symbols. Hammas's art often reflects the southern region of Saudi Arabia, specifically Asir, known for its rich natural beauty, customs, and colorful folk art. His paintings vividly portray the environment with bright and attractive colors, influenced by the local culture, traditions, and crafts." , comment:  ""), paintingStory: NSLocalizedString( "In composition 1 (1988), Hammas captures a glimpse of the old neighborhoods in dim morning light. The painting presents a harmonious interplay of various elements within the urban landscape each blending into another In composition 2( 1988), Hammas continues exploring old houses overlapping one. another depicting their different sizes and the simplicity of one predominant color the presence of blue behind the buildings in varying degrees of light symbolizes the overlap of light and darkness. This interplay between light and heat on the black", comment:  "") , paintingDescription: NSLocalizedString( "Oil on paper.The one on the left features a complex interplay of dark and neutral tones, with overlapping geometric shapes that create an almost architectural feel. The right painting contrasts with brighter blues and yellows, yet it also employs geometric abstraction to depict what could be an urban landscape. Both works play with form and space, creating depth and rhythm through the juxtaposition of shapes and colors.", comment:  ""))
    
    
]
